"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DJANGO_DEBUG')

ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS')

AUTH_USER_MODEL = 'game_api.User'

# In development, accept any Host header (LAN IP, container name, tunnel, etc.)
# so the app is reachable however you browse to it.
if DEBUG and '*' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('*')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	'django.contrib.sites',
	# Third-party
	'rest_framework',
	'channels',
    'django_erd_generator',
	# Authentication
	'allauth',
	'allauth.account',
	'allauth.socialaccount',
	'allauth.socialaccount.providers.google',
	'game_api.providers.fortytwo',
	'dj_rest_auth',
	'dj_rest_auth.registration',
	# Local
	'game_api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
	# Serves STATIC_ROOT directly from the app process — there's no separate
	# nginx/CDN in front of Render, so without this /static/ 404s whenever
	# DEBUG=False (Django's dev static server only runs under DEBUG).
	'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'allauth.account.middleware.AccountMiddleware',
	'game_api.middleware.UpdateLastSeenMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Searched before app templates, so account/email/* here overrides
        # allauth's (game_api sits after allauth in INSTALLED_APPS and can't).
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'

REDIS_URL = env('REDIS_URL')

CHANNEL_LAYERS = {
	'default': {
		'BACKEND': 'channels_redis.core.RedisChannelLayer',
		'CONFIG': {
			'hosts': [{'address': REDIS_URL, 'socket_timeout': 30}],
		},
	}
}

# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': env.db(
        'DATABASE_URL',
        default='postgres://transcendence:transcendence@db:5432/transcendence'
	)
}

# Keep the connection instead of dialling a new one for every request and every
# card played. Django's default is 0 — open, query, hang up — which is free next
# to a database on the same machine and expensive next to a managed one: opening
# it costs a TLS handshake and several round trips, measured at roughly three
# times what the query itself takes. It was most of the delay between playing a
# card and seeing it move.
#
# CONN_HEALTH_CHECKS is what makes reuse safe: a connection the server closed
# while it sat idle is detected and replaced, instead of failing one request.
DATABASES['default']['CONN_MAX_AGE'] = env.int('DJANGO_CONN_MAX_AGE', default=60)
DATABASES['default']['CONN_HEALTH_CHECKS'] = True

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
	'django.contrib.auth.backends.ModelBackend',
	'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['username*', 'email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'optional'
# Otherwise allauth prefixes every subject with "[<Site.name>] ", i.e. "[example.com] ".
ACCOUNT_EMAIL_SUBJECT_PREFIX = ''
ACCOUNT_ADAPTER = 'game_api.adapters.AccountAdapter'
SOCIALACCOUNT_ADAPTER = 'game_api.adapters.SocialAccountAdapter'

SOCIALACCOUNT_PROVIDERS = {
	'google': {
		'SCOPE': ['profile', 'email'],
		'APP': {
			'client_id': env('GOOGLE_OAUTH_CLIENT_ID', default=''),
			'secret': env('GOOGLE_OAUTH_CLIENT_SECRET', default=''),
		},
	},
	'fortytwo': {
		'APP': {
			'client_id': env('FORTYTWO_OAUTH_CLIENT_ID', default=''),
			'secret': env('FORTYTWO_OAUTH_CLIENT_SECRET', default=''),
		},
	},
}
SOCIALACCOUNT_LOGIN_ON_GET = True

# Signing in with Google on an address that already has a password account logs
# into that account, and connects the provider to it so it keeps working if the
# address changes later. Without this, allauth refuses to touch the existing
# account and drops the person into its own bare signup form — which is what
# used to happen, pre-filled with a username they never chose.
#
# The trade is stated plainly in allauth's own docs: this trusts the provider
# completely, because a dishonest one could sign into any account by claiming
# its address. It only applies to an address the provider itself reports as
# verified, and Google reports that. Our 42 provider does not say it yet
# (game_api/providers/fortytwo/provider.py), so 42 still takes the long way.
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

REST_AUTH = {
	'SESSION_LOGIN': True,
	'USE_JWT': False,
	'TOKEN_MODEL': None,
	'REGISTER_SERIALIZER': 'game_api.serializers.RegisterSerializer',
	'PASSWORD_RESET_SERIALIZER': 'game_api.serializers.PasswordResetSerializer',
	'USER_DETAILS_SERIALIZER': 'game_api.serializers.UserDetailsSerializer',
}

REST_FRAMEWORK = {
	'DEFAULT_AUTHENTICATION_CLASSES': [
		'rest_framework.authentication.SessionAuthentication',
	],
	'DEFAULT_PERMISSION_CLASSES': [
		'rest_framework.permissions.IsAuthenticated',
	],
}

SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
CSRF_TRUSTED_ORIGINS = env.list('DJANGO_CSRF_TRUSTED_ORIGINS', default=[])
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# The deployment sits behind Render's router, which passes the host the visitor
# typed in X-Forwarded-Host. Trusting it is what keeps request.build_absolute_uri()
# right, and that is what allauth builds OAuth callback URLs from and what avatar
# URLs are made absolute against. Only safe because nothing reaches this process
# except through that router.
USE_X_FORWARDED_HOST = True

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Django's default (PBKDF2, 1.5M iterations) costs ~0.2s here and ~2.5s on
# Render's CPU, which every login and signup paid for. Argon2 is both stronger
# and an order of magnitude cheaper. PBKDF2 stays listed so existing passwords
# still verify — Django rewrites each one to Argon2 on its owner's next login.
PASSWORD_HASHERS = [
	'game_api.hashers.Argon2Hasher',
	'django.contrib.auth.hashers.PBKDF2PasswordHasher',
	'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Defining STORAGES replaces Django's defaults wholesale, so 'default' must be
# listed again — without it every media save (avatar upload, OAuth signup
# picture) raises InvalidStorageError.
STORAGES = {
	'default': {
		# Uploads go in the database. Nothing that runs this app has a disk that
		# outlives a deploy, and a file written to one disappears without an
		# error (game_api/storage.py,
		# docs/adr/0005-uploaded-files-live-in-the-database.md).
		'BACKEND': 'game_api.storage.DatabaseStorage',
	},
	'staticfiles': {
		'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
	},
}

# Media files (user uploads, e.g. profile avatars)
# https://docs.djangoproject.com/en/6.1/topics/files/

MEDIA_URL = 'media/'
# Uploads are in the database, so nothing writes here any more. It is left for
# the one thing that still reads it: `manage.py import_media_to_db`, which walks
# this directory once to bring files saved before the move across.
MEDIA_ROOT = env('DJANGO_MEDIA_ROOT', default=str(BASE_DIR / 'media'))


# The built single-page app
# Set only where this process is also the web server — the deployed site, where
# the page, /api, /media and /ws all have to answer on one origin, because a
# static host in front of Django cannot carry a WebSocket upgrade through
# (docs/adr/0004-one-origin-in-production.md). Unset locally: `make up` gives the
# app to the Vite dev server and nginx serves the built files in prod compose.

FRONTEND_DIST = env('DJANGO_FRONTEND_DIST', default='')

if FRONTEND_DIST:
	# Serves dist/ at the site root, so /assets/index-COJ6jVha.js resolves to a
	# file. A URL with no file behind it falls through to Django, where the
	# catch-all in core/urls.py answers with index.html and the router takes over.
	WHITENOISE_ROOT = FRONTEND_DIST

	# Vite and collectstatic both put a content hash in the filename, so a changed
	# file arrives under a new name and the old name can be cached for ever — what
	# nginx does with /assets/ in docker/nginx/nginx.prod.conf. Setting this
	# *replaces* WhiteNoise's own test, which only recognises collectstatic's
	# `base.31652d68a9de.css` under /static/, so both forms are spelled out here.
	WHITENOISE_IMMUTABLE_FILE_TEST = r'^/(assets/.*-|static/.*\.)[\w-]{8,}\.\w+$'


# Background work
# See game_api.background — threads, not a queue. On by default, including in
# the tests: nothing overrides it, so a background task really does run on its
# own thread there too. Turn it off to make every task synchronous.

RUN_TASKS_IN_BACKGROUND = env.bool('DJANGO_RUN_TASKS_IN_BACKGROUND', default=True)

# How long a disconnected player's seat is held before the lobby hands off the
# host (or closes the room, if they were alone) — long enough to survive a
# page refresh.
GAME_DISCONNECT_GRACE_SECONDS = env.int('DJANGO_GAME_DISCONNECT_GRACE_SECONDS', default=10)

# How many people may watch one room. A system limit, not a room setting: the
# Create room dialog does not offer it, so there is no column for it either —
# the lobby just reports it so the client does not have to keep its own copy.
GAME_MAX_SPECTATORS = env.int('DJANGO_GAME_MAX_SPECTATORS', default=6)


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

FRONTEND_URL = env('FRONTEND_URL', default='http://localhost:5173').rstrip('/')

DEFAULT_FROM_EMAIL = env('DJANGO_DEFAULT_FROM_EMAIL', default='no-reply@localhost')

if env.bool('DJANGO_EMAIL_USE_SMTP', default=False):
	MAILERS = {
		'default': {
			'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
			'OPTIONS': {
				'host': env('EMAIL_HOST'),
				'port': env.int('EMAIL_PORT', default=587),
				'use_tls': env.bool('EMAIL_USE_TLS', default=True),
				'username': env('EMAIL_HOST_USER'),
				'password': env('EMAIL_HOST_PASSWORD'),
			},
		},
	}
else:
	MAILERS = {
		'default': {
			'BACKEND': 'django.core.mail.backends.console.EmailBackend',
		},
	}

# With DEBUG off, Django hands an unhandled exception to the `django.request`
# logger and returns the plain 500 page. With no LOGGING configured that logger
# has nowhere to write, so the traceback is built and then dropped: the response
# says nothing and `docker compose logs backend` shows only uvicorn's access
# lines. Sending it to the console works with DEBUG off too, which is the point:
# in production DEBUG must stay off, and this is the only way a 500 there ever
# explains itself.
LOGGING = {
	'version': 1,
	'disable_existing_loggers': False,
	'formatters': {
		'verbose': {
			'format': '[{asctime}] {levelname} {name}: {message}',
			'style': '{',
		},
	},
	'handlers': {
		'console': {
			'class': 'logging.StreamHandler',
			'formatter': 'verbose',
		},
	},
	'loggers': {
		'django.request': {
			'handlers': ['console'],
			'level': 'ERROR',
			'propagate': False,
		},
		# Our own code. Without an entry here these records reach the root
		# logger, which has no handler, so Python's last-resort handler prints
		# them bare to stderr — no timestamp, no logger name, and nothing below
		# WARNING at all. That matters for the places that deliberately carry on
		# after a failure, `game_api.spectators` above all: an unreachable Redis
		# now degrades to a count of zero instead of a 500, and the log line is
		# the only thing left that says so.
		'game_api': {
			'handlers': ['console'],
			'level': 'INFO',
			'propagate': False,
		},
	},
}
