"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY', default='django-insecure-826$9gpgvh)y#3bv*occ(_#z#24)q%*g==)tn2m1)-jtnvb(%b')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DJANGO_DEBUG', default=True)

ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=[])

AUTH_USER_MODEL = 'game_api.User'

# In development, accept any Host header (LAN IP, container name, tunnel, etc.)
# so the app is reachable however you browse to it.
if DEBUG and '*' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('*')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	'django.contrib.sites',
	# Third-party
	'rest_framework',
	'channels',
	# Authentication
	'allauth',
	'allauth.account',
	'allauth.socialaccount',
	'allauth.socialaccount.providers.google',
	'game_api.providers.fortytwo',
	'dj_rest_auth',
	'dj_rest_auth.registration',
	# Local
	'game_api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'

CHANNEL_LAYERS = {
	'default': {
		'BACKEND': 'channels_redis.core.RedisChannelLayer',
		'CONFIG': {
			'hosts': [env('REDIS_URL', default='redis://redis:6379/0')],
		},
	}
}

# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': env.db(
        'DATABASE_URL',
        default='postgres://transcendence:transcendence@localhost:5432/transcendence'
	)
}

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
	'django.contrib.auth.backends.ModelBackend',
	'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['username*', 'email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_ADAPTER = 'game_api.adapters.AccountAdapter'
SOCIALACCOUNT_ADAPTER = 'game_api.adapters.SocialAccountAdapter'

SOCIALACCOUNT_PROVIDERS = {
	'google': {
		'SCOPE': ['profile', 'email'],
		'APP': {
			'client_id': env('GOOGLE_OAUTH_CLIENT_ID', default=''),
			'secret': env('GOOGLE_OAUTH_CLIENT_SECRET', default=''),
		},
	},
	'fortytwo': {
		'APP': {
			'client_id': env('FORTYTWO_OAUTH_CLIENT_ID', default=''),
			'secret': env('FORTYTWO_OAUTH_CLIENT_SECRET', default=''),
		},
	},
}
SOCIALACCOUNT_LOGIN_ON_GET = True

REST_AUTH = {
	'SESSION_LOGIN': True,
	'USE_JWT': False,
	'TOKEN_MODEL': None,
	'REGISTER_SERIALIZER': 'game_api.serializers.RegisterSerializer',
	'PASSWORD_RESET_SERIALIZER': 'game_api.serializers.PasswordResetSerializer',
}

REST_FRAMEWORK = {
	'DEFAULT_AUTHENTICATION_CLASSES': [
		'rest_framework.authentication.SessionAuthentication',
	],
	'DEFAULT_PERMISSIONS_CLASSES': [
		'rest_framework.permissions.IsAuthenticated',
	],
}

SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
CSRF_TRUSTED_ORIGINS = env.list('DJANGO_CSRF_TRUSTED_ORIGINS', default=[])
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user uploads, e.g. profile avatars)
# https://docs.djangoproject.com/en/6.1/topics/files/

MEDIA_URL = 'media/'
MEDIA_ROOT = env('DJANGO_MEDIA_ROOT', default=str(BASE_DIR / 'media'))


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

FRONTEND_URL = env('FRONTEND_URL', default='http://localhost:5173').rstrip('/')

DEFAULT_FROM_EMAIL = env('DJANGO_DEFAULT_FROM_EMAIL', default='no-reply@localhost')

if env.bool('DJANGO_EMAIL_USE_SMTP', default=False):
	EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
	EMAIL_HOST = env('EMAIL_HOST')
	EMAIL_PORT = env.int('EMAIL_PORT', default=587)
	EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
	EMAIL_HOST_USER = env('EMAIL_HOST_USER')
	EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
else:
	EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
