# Generated by Django 6.1 on 2026-08-19 14:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('max_participants', models.PositiveSmallIntegerField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.TextField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=40)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('oauth_provider', models.CharField(blank=True, max_length=20, null=True)),
                ('oauth_id', models.TextField(blank=True, null=True)),
                ('totp_secret_encrypted', models.BinaryField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('pt', 'Portuguese')], default='en', max_length=5)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=5)),
                ('accepted_privacy_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tournament_round', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('mode', models.CharField(blank=True, max_length=32)),
                ('join_code', models.CharField(blank=True, max_length=8, null=True)),
                ('max_seats', models.PositiveSmallIntegerField()),
                ('starting_hand_size', models.PositiveSmallIntegerField()),
                ('turn_timer_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stacking_draw_two', models.BooleanField(default=False)),
                ('jump_in', models.BooleanField(default=False)),
                ('draw_until_playable', models.BooleanField(default=False)),
                ('seven_zero', models.BooleanField(default=False)),
                ('extra_rules', models.JSONField(blank=True, null=True)),
                ('deck', models.JSONField(blank=True, null=True)),
                ('discard', models.JSONField(blank=True, null=True)),
                ('active_color', models.CharField(blank=True, choices=[('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('wild', 'Wild')], max_length=6, null=True)),
                ('direction', models.SmallIntegerField(default=1)),
                ('current_seat', models.SmallIntegerField(blank=True, null=True)),
                ('pending_draw_count', models.SmallIntegerField(default=0)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='game_api.tournament')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_games', to='game_api.user')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_won', to='game_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('pk', models.CompositePrimaryKey('tournament_id', 'user_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('seed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('final_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='game_api.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries', to='game_api.user')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_created', to='game_api.user'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_won', to='game_api.user'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='game_api.game')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='game_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('human', 'Human'), ('ai', 'AI')], default='human', max_length=5)),
                ('ai_level', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=6, null=True)),
                ('seat', models.SmallIntegerField()),
                ('display_name', models.CharField(blank=True, max_length=40)),
                ('hand', models.JSONField(blank=True, null=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('declared_last_card', models.BooleanField(default=False)),
                ('finish_position', models.SmallIntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game_api.game')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_seats', to='game_api.user')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game', 'seat'), name='unique_game_seat')],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('blocked', 'Blocked')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('addressee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to='game_api.user')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_sent', to='game_api.user')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('requester', 'addressee'), name='unique_friendship_pair')],
            },
        ),
    ]
